-- Finance OS V1.5 schema expansion

CREATE TABLE `RecurringExpense` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `category` VARCHAR(191) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'TRY',
  `billingCycle` ENUM('MONTHLY', 'YEARLY') NOT NULL,
  `billingAnchorDay` INTEGER NULL,
  `nextPayment` DATETIME(3) NOT NULL,
  `autopay` BOOLEAN NOT NULL DEFAULT false,
  `isEssential` BOOLEAN NOT NULL DEFAULT true,
  `status` ENUM('ACTIVE', 'PAUSED', 'CANCELED') NOT NULL DEFAULT 'ACTIVE',
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `IncomeSource` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'TRY',
  `billingCycle` ENUM('MONTHLY', 'YEARLY') NOT NULL,
  `payday` INTEGER NULL,
  `isPrimary` BOOLEAN NOT NULL DEFAULT false,
  `status` ENUM('ACTIVE', 'PAUSED', 'CANCELED') NOT NULL DEFAULT 'ACTIVE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BudgetMonth` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `month` DATETIME(3) NOT NULL,
  `plannedIncome` DOUBLE NOT NULL DEFAULT 0,
  `fixedCommitments` DOUBLE NOT NULL DEFAULT 0,
  `debtCommitments` DOUBLE NOT NULL DEFAULT 0,
  `freeCash` DOUBLE NOT NULL DEFAULT 0,
  `bufferTarget` DOUBLE NOT NULL DEFAULT 0,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `BudgetMonth_userId_month_key`(`userId`, `month`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BudgetAlert` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `type` ENUM('UPCOMING_PAYMENT', 'BUDGET_PRESSURE', 'RENEWAL', 'PRICE_CHANGE') NOT NULL,
  `state` ENUM('OPEN', 'DISMISSED') NOT NULL DEFAULT 'OPEN',
  `title` VARCHAR(191) NOT NULL,
  `content` TEXT NOT NULL,
  `dueDate` DATETIME(3) NULL,
  `channel` VARCHAR(191) NOT NULL DEFAULT 'IN_APP',
  `dedupeKey` VARCHAR(191) NOT NULL,
  `metadata` JSON NULL,
  `dismissedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `BudgetAlert_dedupeKey_key`(`dedupeKey`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Subscription`
  MODIFY `billingCycle` ENUM('MONTHLY', 'YEARLY') NOT NULL,
  ADD COLUMN `brandKey` VARCHAR(191) NULL,
  ADD COLUMN `providerDomain` VARCHAR(191) NULL,
  ADD COLUMN `logoUrl` VARCHAR(191) NULL,
  ADD COLUMN `color` VARCHAR(191) NOT NULL DEFAULT '#27272A',
  ADD COLUMN `billingAnchorDay` INTEGER NULL,
  ADD COLUMN `autopay` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `status` ENUM('ACTIVE', 'PAUSED', 'CANCELED') NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN `notes` TEXT NULL,
  ADD COLUMN `lastAmount` DOUBLE NULL,
  ADD COLUMN `monthlyNormalizedAmount` DOUBLE NULL,
  ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `RecurringExpense`
  ADD CONSTRAINT `RecurringExpense_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `IncomeSource`
  ADD CONSTRAINT `IncomeSource_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BudgetMonth`
  ADD CONSTRAINT `BudgetMonth_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BudgetAlert`
  ADD CONSTRAINT `BudgetAlert_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
